### ISSUE TITLE
Checkout Transparente

### ISSUE THREAD

**Issue by gusilveiramp** [santigraviano/laravel-mercadopago#1]
Hola amigo, gran trabajo!
Instalado en laravel 5.2 y parece que funciona perfectamente.
Mi pregunta es la siguiente:

El proyecto está terminado? ¿Puedo utilizar la voluntad?
Es posible utilizarmos Mercado Envios con esta API?

Ya, gracias inmensamente por su trabajo.
Abrazos!

Olá amigo, excelente trabalho!
Instalei no Laravel 5.2 e parece funcionar perfeitamente.
Minha dúvida é a seguinte:

O projeto está finalizado? Posso usar tranquilamente?
É possível efetuar checkout transparente?
É possível utilizar Mercado Envios com essa API?

Desde já, te agradeço imensamente pelo trabalho realizado.
Abraços!

**Comment by santigraviano** [comment]
Hola, gracias por utlilizar mi repo.
Actualmente solo funciona con MercadoPago.
Este repo esta actulizado a la ultima version de la API de MercadoPago, asi
que podes usarlo sin riesgos.
Se le pueden agregar mas ejemplos, como un basic checkout. Yo no lo hice
porque creo que sale del objectivo del repositorio.

Saludos.

**Comment by gusilveiramp** [comment]
Gracias por la respuesta y, de nuevo, gracias por el excelente trabajo.
Cuando traté de usar el ejemplo de débito, tengo un error en la devolución:
MercadoPagoException in MP.php line 532: Invalid value for back_url, must be a valid URL

La 'back_url' que estoy usando es http://localhost:8000/mercadopago/preapproval

El error es debido al hecho de que estoy utilizando una URL local (XAMPP servidor)?
Si este es el problema, ¿cómo activo el modo de de Sandbox o el modo de producción?

**Comment by santigraviano** [comment]
Exactamente, para que las back_url funcionen tienen que ser accesibles para
MercadoPago. En este caso podes poner tu ip publica como back_url, por
ejemplo: http://123.123.123.123/mercadopago/preapproval

Podes activar el modo sandbox con MP::sandbox_mode(TRUE);

Esto sirve para testear las notificaciones que llegan desde MercadoPago, ya
que si realizas pagos en sandbox activado, las notificaciones son de prueba
y si intentas acceder a ellas sin el sandbox activado vas a recibir un
error de que el recurso no existe.
